# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Data Visualization
site_url: https://github.com/filipinascimento/dataviz
site_author: Filipi Nascimento Silva
site_description:

# Repository
repo_name: filipinascimento/dataviz
repo_url: https://github.com/filipinascimento/dataviz
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  # - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: en
  logo: images/dv.png
  favicon: images/dv.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yyahn/
    - icon: fontawesome/solid/globe
      link: https://yongyeol.com/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - index.md
    - communication.md
    - "1: Introduction":
        - m01-intro/class.md
        - m01-intro/lab01.ipynb
        - m01-intro/lab01supp-python_review.ipynb





